// <auto-generated />
using System;
using Eblcu.Bi.EntityFrameworkCore.SecondDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eblcu.Bi.Migrations.SecondDb
{
    [DbContext(typeof(SecondDbContext))]
    [Migration("20180913145833_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Eblcu.Bi.Test.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime")
                        .HasMaxLength(65);

                    b.Property<DateTime?>("DeletionTime")
                        .HasMaxLength(65);

                    b.Property<bool>("IsDeleted")
                        .HasMaxLength(65);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasMaxLength(65);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.HasKey("Id");

                    b.ToTable("Products","CMS");
                });
#pragma warning restore 612, 618
        }
    }
}
